/**
 * Codec vectors ported from react-native-nfc-manager's own test suite
 * (docs/react-native-nfc-manager/__tests__/ndef.test.js) — independently
 * hand-encoded NDEF Forum byte streams, not generated by this project's own
 * encoder. §6a's codec vectors are otherwise all authored by this repo
 * (still hand-encoded per the RTD specs, not round-tripped through our own
 * code, but written with knowledge of our own decoder's expectations); these
 * three vectors come from a separate, independently-maintained project's
 * test fixtures, so they cross-check our decoder against an interpretation
 * of the NFC Forum spec that isn't ours.
 *
 * The source vectors are full NDEF *message* byte streams (record header
 * framing — MB/ME/CF/SR/TNF flags, type-length, payload-length — for one or
 * more concatenated records), one level below this project's
 * `NdefWireRecord` boundary type (§5b), which already has TNF/type/payload
 * split out. Each vector below documents the manual short-record framing
 * parse (flags byte -> TNF; typeLength byte; payloadLength byte; type bytes;
 * payload bytes) that extracts the `NdefWireRecord` fields our codec
 * actually consumes, so the byte-level provenance stays traceable back to
 * the original array literal.
 */
import {bytesToBase64, TNF} from './ndef-wire';
import {decodeRecord} from './well-known-records';

describe('vectors ported from react-native-nfc-manager/__tests__/ndef.test.js', () => {
  test('text record: "hello, world" (textMessageHelloWorld)', () => {
    // Source: [209, 1, 15, 84, 2, 101, 110, 104, 101, 108, 108, 111, 44, 32,
    //          119, 111, 114, 108, 100]
    // flags/TNF byte 209 = 0b11010001 -> MB=1 ME=1 SR=1 TNF=001 (WELL_KNOWN)
    // typeLength=1, payloadLength=15, type="T", payload=[2,'e','n',...'hello, world']
    const record = {
      tnf: TNF.WELL_KNOWN,
      type: bytesToBase64(new Uint8Array([84])), // "T"
      id: '',
      payload: bytesToBase64(
        new Uint8Array([
          2, 101, 110, 104, 101, 108, 108, 111, 44, 32, 119, 111, 114, 108, 100,
        ]),
      ),
    };
    const decoded = decodeRecord(record);
    expect(decoded.recordType).toBe('text');
    expect(decoded.lang).toBe('en');
    expect(decoded.encoding).toBe('utf-8');
    expect(new TextDecoder().decode(decoded.data)).toBe('hello, world');
  });

  test('URI record: "http://nodejs.org" (urlMessageNodeJSorg)', () => {
    // Source: [209, 1, 11, 85, 3, 110, 111, 100, 101, 106, 115, 46, 111,
    //          114, 103]
    // flags/TNF byte 209 = WELL_KNOWN, type="U", payload=[3,'nodejs.org']
    // (prefix code 3 = "http://" per the NFC Forum URI RTD prefix table)
    const record = {
      tnf: TNF.WELL_KNOWN,
      type: bytesToBase64(new Uint8Array([85])), // "U"
      id: '',
      payload: bytesToBase64(
        new Uint8Array([3, 110, 111, 100, 101, 106, 115, 46, 111, 114, 103]),
      ),
    };
    const decoded = decodeRecord(record);
    expect(decoded.recordType).toBe('url');
    expect(new TextDecoder().decode(decoded.data)).toBe('http://nodejs.org');
  });

  test('multi-record message: text + uri + mime (multipleRecordMessage)', () => {
    // Source is one concatenated NDEF message (multipleRecordMessage in the
    // original) with three short records back-to-back: a text record
    // ("hello, world"), a URI record ("http://nodejs.org"), and a MIME
    // record (text/json, {"message": "hello, world"}). Framing flags differ
    // per record (first has MB only, middle has neither MB nor ME, last has
    // ME + a longer TNF for MIME_MEDIA=2), but this project's codec operates
    // per-record on already-split NdefWireRecord fields (§5b) — native/the
    // wire format is responsible for message-level framing, not this file —
    // so each record is exercised individually here exactly as `ndef-wire.ts`
    // would receive it.
    const textRecord = decodeRecord({
      tnf: TNF.WELL_KNOWN,
      type: bytesToBase64(new Uint8Array([84])), // "T"
      id: '',
      payload: bytesToBase64(
        new Uint8Array([
          2, 101, 110, 104, 101, 108, 108, 111, 44, 32, 119, 111, 114, 108, 100,
        ]),
      ),
    });
    expect(textRecord.recordType).toBe('text');
    expect(new TextDecoder().decode(textRecord.data)).toBe('hello, world');

    const uriRecord = decodeRecord({
      tnf: TNF.WELL_KNOWN,
      type: bytesToBase64(new Uint8Array([85])), // "U"
      id: '',
      payload: bytesToBase64(
        new Uint8Array([3, 110, 111, 100, 101, 106, 115, 46, 111, 114, 103]),
      ),
    });
    expect(uriRecord.recordType).toBe('url');
    expect(new TextDecoder().decode(uriRecord.data)).toBe('http://nodejs.org');

    // MIME record: type="text/json" (TNF=2 MIME_MEDIA), payload is the raw
    // JSON text bytes verbatim (MIME records carry payload bytes as-is, no
    // RTD-specific framing).
    const mimeType = 'text/json';
    const mimeText = '{"message": "hello, world"}';
    const mimeRecord = decodeRecord({
      tnf: TNF.MIME_MEDIA,
      type: bytesToBase64(new TextEncoder().encode(mimeType)),
      id: '',
      payload: bytesToBase64(new TextEncoder().encode(mimeText)),
    });
    expect(mimeRecord.recordType).toBe('mime');
    expect(mimeRecord.mediaType).toBe(mimeType);
    expect(new TextDecoder().decode(mimeRecord.data)).toBe(mimeText);
  });
});
